/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIAssistant: typeof import('./src/components/AIAssistant.vue')['default']
    Alert: typeof import('./src/components/common/Alert.vue')['default']
    AppLoading: typeof import('./src/components/AppLoading.vue')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    FriendManager: typeof import('./src/components/FriendManager.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    PageError: typeof import('./src/components/common/PageError.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
